server:
    port: 8082
spring:
    application:
    name: discovery
   
info:
  app:
    description: This is an infrastructure service for discovery microservices
    name: Discovery Service
    version: 1.0.0
       
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
        defaultZone: http://localhost:8082/eureka/
    instance:
    hostname: localhost

#management:
#  endpoints:
#    web:
#      exposure:
#      include: '*'
