server:
  port: 8101

info:
  app:
    description: Product Service
    name: Product Service
    version: 1.0.0
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true    
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/


